# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "7.0.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "9.0.1"
    firewall:
      repo: "puppetlabs/firewall"
      ref: "6.0.0"
    systemd:
      repo: "puppet/systemd"
      ref: "6.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.4.1"
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'

