---
stages:
  - syntax
  - unit
  - g10k_deploy
  - send_notification

default:
  cache:
    paths:
      - vendor/bundle

  before_script: &before_script
    - bundle -v
    - rm Gemfile.lock || true
    - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
    - "# Set `rubygems_version` in the .sync.yml to set a value"
    - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
    - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
    - gem --version
    - bundle -v
    - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

validate lint check rubocop-Ruby 2.5.7-Puppet ~> 6:
  stage: syntax
  image: ruby:2.5.7
  script:
    - bundle exec rake validate lint check rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 6'
  tags:
    - shared-docker-runner-prod-gitlab-runner02

parallel_spec-Ruby 2.5.7-Puppet ~> 6:
  stage: unit
  image: ruby:2.5.7
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 6'
  tags:
    - shared-docker-runner-prod-gitlab-runner02

validate lint check rubocop-Ruby 2.7.2-Puppet ~> 7:
  stage: syntax
  image: ruby:2.7.2
  script:
    - bundle exec rake validate lint check rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 7'
  tags:
    - shared-docker-runner-prod-gitlab-runner02

parallel_spec-Ruby 2.7.2-Puppet ~> 7:
  stage: unit
  image: ruby:2.7.2
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 7'
  tags:
    - shared-docker-runner-prod-gitlab-runner02

# custom internal jobs
job_deploy:
  stage: g10k_deploy
  when: on_success
  script:
    - ${HOME_RUNNER}/bin/ci2puppet.sh ${CI_PROJECT_NAME} ${CI_COMMIT_REF_NAME}
  tags:
    - gitlab-runner02-shell01-tag1

job_notification:
  stage: send_notification
  when: on_failure
  variables:
    MSG: "*ERROR on Commit ID*: ${CI_COMMIT_SHA}\n*Commit Author*: ${GITLAB_USER_NAME}\n*Commit Title*: ${CI_COMMIT_TITLE}\n*Repository*: ${CI_PROJECT_NAME}\n*Branch*: ${CI_COMMIT_REF_NAME}"
  script:
    - echo -e "${MSG}" > ${HOME_RUNNER}/${CI_PROJECT_NAME}_msg.txt
    - cat ${HOME_RUNNER}/${CI_PROJECT_NAME}_rev_count_msg.txt >> ${HOME_RUNNER}/${CI_PROJECT_NAME}_msg.txt
    - cat ${HOME_RUNNER}/msg_closure.txt >> ${HOME_RUNNER}/${CI_PROJECT_NAME}_msg.txt
    - /usr/local/bin/upload_to_slack.sh ${HOME_RUNNER}/${CI_PROJECT_NAME}_msg.txt post "Puppet CI Error" "${DEVOPS_CHANNEL}" ${DEVOPSBOT_TOKEN} ERROR
    - cat ${HOME_RUNNER}/${CI_PROJECT_NAME}_msg.txt | mail -s "Puppet CI Error on Repository ${CI_PROJECT_NAME}" $RCPT
  tags:
    - gitlab-runner02-shell01-tag2


